config/routes.rb
Rails.application.routes.draw do
  resources :students do
    resources :enrollments, only: [:index, :new, :create]
  end

  resources :enrollments, only: [:update, :destroy]


  devise_for :users
  resources :sections do 
    collection do 
      get "search"
    end
  end

  resources :courses do 
    collection do 
      get "search"
    end
  end

  resources :professors do
    collection do
      get "search"
    end 
  end
  root to: "professors#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/professor.rb
class Professor < ApplicationRecord
  has_many :sections
  has_many :courses, through: :sections

  validates :name, :department,  presence: true
  validates :name, length: { minimum: 3 }
  validates :department, length: { minimum: 3 }

  validates :department, format: { with: /\A[a-z A-Z]+\z/ }

  #only one professor with the same name in the department
  validates :name, uniqueness: { scope: :department }
end

app/controllers/professors_controller.rb
class ProfessorsController < ApplicationController
  before_action :authenticate_user! 
  before_action :set_professor, only: [:show, :edit, :update, :destroy]

  # GET /professors
  # GET /professors.json
  def index
    @professors = Professor.all
  end

  # GET /professors/1
  # GET /professors/1.json
  def show
    @profs_courses = {};
    sections = @professor.sections

    sections.each do |section| 
      if @profs_courses[section.course].nil?
        @profs_courses[section.course] = [];
      end
      @profs_courses[section.course].push section

    end
  end

  # GET /professors/new
  def new
    @professor = Professor.new
  end

  # GET /professors/1/edit
  def edit
  end

  # POST /professors
  # POST /professors.json
  def create
    @professor = Professor.new(professor_params)

    respond_to do |format|
      if @professor.save
        format.html { redirect_to @professor, notice: 'Professor was successfully created.' }
        format.json { render :show, status: :created, location: @professor }
      else
        format.html { render :new }
        format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /professors/1
  # PATCH/PUT /professors/1.json
  def update
    respond_to do |format|
      if @professor.update(professor_params)
        format.html { redirect_to @professor, notice: 'Professor was successfully updated.' }
        format.json { render :show, status: :ok, location: @professor }
      else
        format.html { render :edit }
        format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /professors/1
  # DELETE /professors/1.json
  def destroy
    @professor.destroy
    respond_to do |format|
      format.html { redirect_to professors_url, notice: 'Professor was successfully deleted' }
      format.json { head :no_content }
    end
  end


  def search
    searchString = params[:search];
    if(searchString.nil? || searchString.length < 3) 
      @professors = []
    else 
      @professors = Professor.where("name like (?)", "%#{searchString}%").limit(5)
    end 
    respond_to do |format|
      format.json { render json: @professors }
      format.html { render :index}
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_professor
    @professor = Professor.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def professor_params
    params.require(:professor).permit(:name, :department)
  end
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/views/professors/_form.html.erb
<%= form_with(model: professor, local: true) do |form| %>
  <% if professor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(professor.errors.count, "error") %> prohibited this professor from being saved:</h2>

      <ul>
      <% professor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :professor_name %>
  </div>

  <div class="field">
    <%= form.label :department %>
    <%= form.text_field :department, id: :professor_department %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/professors/edit.html.erb
<h1>Editing Professor</h1>

<%= render 'form', professor: @professor %>

<%= link_to 'Show', @professor %> |
<%= link_to 'Back', professors_path %>

app/views/professors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Professors</h1>


<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Department</th>
      <th colspan="2">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @professors.each do |professor| %>
        <tr class="<%= cycle('list_odd', 'list_even')%>" >
        <td><%= link_to professor.name, professor %></td>
        <td><%= professor.department %></td>
        <td><%= link_to 'Edit', edit_professor_path(professor) %></td>
        <td><%= link_to 'Delete', professor, method: :delete, data: 
            { confirm: "Are you sure you want to delete professor #{professor.name}?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= button_to 'Add', new_professor_path, method: :get %>

app/views/professors/new.html.erb
<h1>New Professor</h1>

<%= render 'form', professor: @professor %>

<%= link_to 'Back', professors_path %>

app/views/professors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
    <strong>Name:</strong>
    <%= @professor.name %>
</p>

<p>
    <strong>Department:</strong>
    <%= @professor.department %>
</p>
<h3>Courses</h3>
<ul>
    <% @profs_courses.each do |course,sections| %>
        <li><%= link_to course.name, course %></li>
        <ul>
            <% sections.each do |section| %>
                <li>
                    <%= link_to section.time.strftime("%l:%M %p"), section %>
                    <ul>
                        <% section.students.each do |student| %>
                            <li><%= student.name %></li>
                        <% end %>
                    </ul>
                </li>
            <% end %>
        </ul>
    <% end %>
</ul>
<%= link_to 'Edit', edit_professor_path(@professor) %> |
<%= link_to 'Back', professors_path %>