config/routes.rb
Rails.application.routes.draw do
  resources :students do
    resources :enrollments, only: [:index, :new, :create]
  end

  resources :enrollments, only: [:update, :destroy]


  devise_for :users
  resources :sections do 
    collection do 
      get "search"
    end
  end

  resources :courses do 
    collection do 
      get "search"
    end
  end

  resources :professors do
    collection do
      get "search"
    end 
  end
  root to: "professors#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :student
  belongs_to :section

  #a studnet cannot enroll in the same course twice
  validates :student, uniqueness: { scope: :section }

end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :set_enrollment, only: [:show, :edit, :update, :destroy]

  # GET /enrollments
  # GET /enrollments.json
  def index
    @enrollments = Enrollment.all
  end

  # GET /enrollments/1
  # GET /enrollments/1.json
  def show
  end

  # GET /enrollments/new
  def new
    @enrollment = Enrollment.new
    @student = Student.find(params[:student_id])
    sections = Section.all - @student.sections
    @courses = {}
    sections.each do |section| 
      if @courses[section.course].nil?
        @courses[section.course] = {}
      end
      if @courses[section.course][section.professor].nil?
        @courses[section.course][section.professor] = [];
      end
      @courses[section.course][section.professor].push section
    end 


  end

  # GET /enrollments/1/edit
  def edit
  end

  # POST /enrollments
  # POST /enrollments.json
  def create
    @enrollment = Enrollment.new(enrollment_params)
    @student = Student.find(params[:student_id])
    sections = Section.all - @student.sections

    @courses = {}
    sections.each do |section| 
      if @courses[section.course].nil?
        @courses[section.course] = {}
      end
      if @courses[section.course][section.professor].nil?
        @courses[section.course][section.professor] = [];
      end
      @courses[section.course][section.professor].push section
    end 



    respond_to do |format|
      if @enrollment.save
        format.html { redirect_to student_enrollments_url(@student), notice: 'Enrollment was successfully created.' }
        format.json { render :show, status: :created, location: @enrollment }
      else
        format.html { render :new }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enrollments/1
  # PATCH/PUT /enrollments/1.json
  def update
    @student = Student.find(params[:student_id])
    respond_to do |format|
      if @enrollment.update(enrollment_params)
        format.html { redirect_to @enrollment, notice: 'Enrollment was successfully updated.' }
        format.json { render :show, status: :ok, location: @enrollment }
      else
        format.html { render :edit }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enrollments/1
  # DELETE /enrollments/1.json
  def destroy
    student = @enrollment.student
    @enrollment.destroy
    respond_to do |format|
      format.html { redirect_to student_enrollments_url(student), notice: 'Enrollment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enrollment
      @enrollment = Enrollment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def enrollment_params
      params.require(:enrollment).permit(:student_id, :section_id)
    end
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/views/enrollments/_form.html.erb
<%= form_with(url: new_student_enrollment_path, local: true) do |form| %>
  <% if enrollment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(enrollment.errors.count, "error") %> prohibited this enrollment from being saved:</h2>

      <ul>
      <% enrollment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/enrollments/edit.html.erb
<h1>Editing Enrollment</h1>

<%= render 'form', enrollment: @enrollment %>

<%= link_to 'Show', @enrollment %> |
<%= link_to 'Back', enrollments_path %>

app/views/enrollments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Enrollments</h1>

<table class="table">
    <thead>
        <tr>
            <th>Course Name</th>
            <th>Class time</th>
            <th>Professor</th>
            <th colspan="1"></th>
        </tr>
    </thead>

    <tbody>
        <% @enrollments.each do |enrollment| %>
            <tr>
                <td><%= enrollment.section.course.name %></td>
                <td><%= enrollment.section.time.strftime("%l:%M %p") %></td>
                <td><%= enrollment.section.professor.name %></td>
                <td><%= link_to 'Drop', enrollment, method: :delete, data: { confirm: 'Are you sure you wish to un-enroll?' } %></td>
            </tr>
        <% end %>
    </tbody>
</table>

<br>

<%= link_to 'New Enrollment', new_student_enrollment_path %>

app/views/enrollments/new.html.erb
<h1>New Enrollment</h1>
<% if @enrollment.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(@enrollment.errors.count, "error") %> prohibited this enrollment from being saved:</h2>

        <ul>
            <% @enrollment.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>

<ul>
    <% @courses.each do |course, professors| %>
        <li><%= course.name %></li>
        <ul>
            <% professors.each do |professor, sections| %>
                <li><%= professor.name %></li>
                <ul>
                    <% sections.each do |section| %>
                        <li> 
                            <%= form_with model: [ @student, @enrollment ] do |form|  %>
                                <%= form.hidden_field :section_id, value: section.id  %>
                                <%= form.hidden_field :student_id, value: @student.id  %>
                                <%= section.time.strftime("%l:%M %p")  %>    | <%= form.submit "Enroll", class: "btn-link" %>
                            <% end %></li>
                    <% end %>
                </ul>
            <% end %>
        </ul> 
    <% end %>
</ul>


<%= link_to 'Back', student_enrollments_path %>

app/views/enrollments/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_enrollment_path(@enrollment) %> |
<%= link_to 'Back', student_enrollments_path(@enrollment.student) %>