config/routes.rb
Rails.application.routes.draw do
  resources :students do
    resources :enrollments, only: [:index, :new, :create]
  end

  resources :enrollments, only: [:update, :destroy]


  devise_for :users
  resources :sections do 
    collection do 
      get "search"
    end
  end

  resources :courses do 
    collection do 
      get "search"
    end
  end

  resources :professors do
    collection do
      get "search"
    end 
  end
  root to: "professors#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navigation.html.erb
    <ul class="nav flex-column nav-pills">
        <li class="nav-item">
            <%= link_to 'Professors', professors_path, class: "nav-link #{ "active" if current_page?(professors_path) }" %>
        </li>
        <li class="nav-item">
            <%= link_to 'Courses', courses_path, class: "nav-link #{ "active" if current_page?(courses_path) }" %>
        </li>
        <li class="nav-item">
            <%= link_to 'Sections', sections_path, class: "nav-link #{ "active" if current_page?(sections_path) }" %>
        </li>
        <li class="nav-item">
            <%= link_to 'Students', students_path, class: "nav-link #{ "active" if current_page?(students_path) }" %>
        </li>
    </ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>School</title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    </head>

    <body class="<%= controller.controller_name %>">
        <div id="container" class="container">
            <div id="navheader" class="row">
                <div class="col">
                    <nav class="navbar navbar-expand-lg navbar-light bg-light">
                        <a class="navbar-brand" href="#">The School</a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>

                        <div class="collapse navbar-collapse" id="navbarToggler">
                            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                                <li class="nav-item active">
                                    <%= link_to "Home", root_path, class: "nav-link" %>
                                </li>

                                <% if user_signed_in? %>
                                    <li class="nav-item">
                                        <%= link_to "Edit Profile", edit_user_registration_path , class: "nav-link" %>
                                    </li>
                                    <li class="nav-item">
                                        <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
                                    </li> 

                                <% else %>
                                    <li class="nav-item">
                                        <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
                                    </li> 
                                    <li class="nav-item">
                                        <%= link_to "Create Account", new_user_registration_path, class: "nav-link" %>
                                    </li> 
                                <% end %>
                                </li>
                            </ul>
                            <%
                            if current_page?(professors_path) || current_page?(search_professors_path)
                                searchPath = search_professors_path 
                                searchText = 'Search Professors'
                            elsif current_page?(courses_path) || current_page?(search_courses_path)
                                searchPath = search_courses_path 
                                searchText = 'Search Courses'
                            elsif current_page?(sections_path) || current_page?(search_sections_path)
                                searchPath = search_sections_path 
                                searchText = 'Search Sections'
                            else 
                                searchPath = '#'
                                searchText = 'Search not supported here'
                            end
                        %>
                    <%= form_tag searchPath, method: :get, class: "form-inline my-2 my-lg-0" do %>
                        <%= text_field_tag :search, nil, class: "form-control mr-sm-2", placeholder: searchText %>
                        <%= submit_tag 'Search', class: "btn btn-outline-success my-2 my-sm-0" %>
                    <% end %>
                        </div>
                    </nav>
                </div> 
            </div> 

            <div class="row">
                <div id="sidebar" class="col-xs-3">
                    <%= render 'layouts/navigation' %>
                </div>
                <div id="content" class="col-xs-9">
                    <div>
                        <%= yield %>
                    </div>
                </div> 
            </div>
        </div> 


    </body>
</html>